### ISSUE TITLE
.

### ISSUE THREAD

**Issue by graysuit** [0xyg3n/DarkFender#1]

**Comment by 0xyg3n** [comment]
Sure bud, thanks for your great comment.

Well i was looking for a way to disable windows defender with the simplest way (though registry!) But since Microsoft added a new feature called Windows Defender tampering i simply had to disable that first from registry in order to completely disable windows defender( Again a registry value). But things weren't that easy, since in order to edit the tamper value from registry i had to change the permissions of the specific section to Trusted Installer in order to apply the changes and afterwards i could edit any registry value so i disabled defender tampering and then i disabled windows defender as policy restriction. (After the changes are applied the permissions are rolled back to default) Sadly a reboot is required for the effects to apply. I might find a work around on how to do that without requiring a restart. I would like also to state that i am new in C# and i haven't ever developed a serious project before, i am actually new to OOP programming. I am mostly familiar with scripting languages, but i have to say OOP is game changing for me and i really liked it.

**Comment by graysuit** [comment]
>i had to change the permissions of the specific section to Trusted Installer

You mean you need admin rights to disable defender ?

>i am new in C#

No problem, From my experience scripting guy needs more brain than OOP guy,
Because you need to make situation.
So now C# will be more easy for you,
Joke : Dotnet is made for kids specially. (We don't have to do nothing)

**Comment by 0xyg3n** [comment]
Yes you need administrator access in order to do such actions.

But.... i do have a uac exploit so in my case i don't really have to be, because i can simply can be admin haha...

If you want to keep our conv going add me on Discord: 0xyg3n®#4993

**Comment by cagedh1** [comment]
i use your code,it has error
![image](https://user-images.githubusercontent.com/48586139/88787331-49328980-d1c6-11ea-9bee-e6ed0f02ce2c.png)

**Comment by 0xyg3n** [comment]
> i use your code,it has error
> ![image](https://user-images.githubusercontent.com/48586139/88787331-49328980-d1c6-11ea-9bee-e6ed0f02ce2c.png)

Make sure you run the code as administrator.

**Comment by cagedh1** [comment]
i am sure that i run the code as administrator,but it cant execute

**Comment by cagedh1** [comment]
And you set the app.manifest, now i dont  know why i cant run the code

**Comment by 0xyg3n** [comment]
Are you debugging the code? if yes don't just run it and go check registry if the values have changed. Because this is a permission error, meaning that it can't access something.

**Comment by cagedh1** [comment]
yes, i have debugged the code.i  also check the values but it not changes.i think if i need other opearation?

**Comment by cagedh1** [comment]
Exactly，i dont access to change the values about Features/TamperProtection

**Comment by cagedh1** [comment]
i want to know if your windows version is 1909

**Comment by 0xyg3n** [comment]
of course not , its 2004 latest update.

**Comment by 0xyg3n** [comment]
because the tamper thing applies after some very specific release maybe after 2004

**Comment by cagedh1** [comment]
ok,so  do you know how to disable windows defender in win10 1909?

**Comment by 0xyg3n** [comment]
of course! can you check if there is tamper protection available over settings?

**Comment by cagedh1** [comment]
how to check?  the tamper protection cant be closed by code ?

**Comment by cagedh1** [comment]
My English is a little poor. i wish you can understand me

**Comment by graysuit** [comment]
@0xyg3n I sent you friend request at discord.
